backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "Новости"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Текст", name: "body", widget: "markdown" }

  - name: "books"
    label: "Книги"
    folder: "content/books"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Название книги", name: "title", widget: "string" }
      - { label: "Обложка", name: "cover", widget: "image", required: false }
      - { label: "Статус", name: "status", widget: "select", options: ["Завершено", "В процессе", "Черновик"] }
      - { label: "Жанр", name: "genre", widget: "string", required: false }
      - { label: "Год написания", name: "year", widget: "number", required: false }
      - { label: "Краткое описание", name: "excerpt", widget: "text", required: false }
      - { label: "Полное описание", name: "description", widget: "markdown", required: false }